---
name: Update Pull Request from Branch
description: Updates Pull Request title and body from branch name
author: kigary
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  repo-token:
    description: The GITHUB_TOKEN secret
    required: true
  issue-ticket-regex:
    description: The regex to match Issue ticket in branch name
    required: true
outputs:
  issue-ticket-number:
    description: The Issue ticket number
  pull-request-title:
    description: The Pull Request title
  pull-request-body:
    description: The Pull Request body
runs:
  using: node20
  main: dist/index.js